<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get_package_config_dir</value>
  <value name="encodeutf8">true</value>
  <value name="body">IAlJRGF0YUhhc2hDdXJzb3IgaWRjID0gcGlwZWxpbmUuZ2V0SGFzaEN1cnNvcigpOwoKCi8vIHBp
cGVsaW5lCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
CglTdHJpbmcJa2V5ID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJwa2ci
ICk7CnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsKCS8vIElmIHBhY2thZ2UgbmFtZSBpcyBub3Qg
cHJvdmlkZWQgdXNlIGRlZmF1bHQgcGFja2FnZSB3aGVyZSBzZXJ2aWNlcyBsb2NhdGVkCglpZiAo
a2V5ID09IG51bGwpCgl7CQoJCVZhbHVlcyB2bCA9IFZhbHVlc0VtdWxhdG9yLmdldFZhbHVlcyhw
aXBlbGluZSwga2V5KTsKCQlrZXkgPSBTZXJ2aWNlLmdldFBhY2thZ2VOYW1lKHZsKTsKCX0KCVN0
cmluZyBwa2cgPSBrZXk7CglGaWxlIGZsID0gU2VydmVyQVBJLmdldFBhY2thZ2VDb25maWdEaXIo
cGtnKTsKCVN0cmluZyBjb25maWdfZGlyID0gZmwuZ2V0UGF0aCgpOwoKCXRyeQoJewkKCQkvLyBH
ZXQgbGlzdCBvZiBmaWxlcyBpbiBhIGdpdmUgZGlyZWN0b3J5CiAgICAgICAgRmlsZSBmbmFtZSA9
IG5ldyBGaWxlKGNvbmZpZ19kaXIpOwogICAgICAgIFN0cmluZ1tdIGZpbGVfbGlzdCA9IGZuYW1l
Lmxpc3QoKTsKCQlmbmFtZSA9IG51bGw7CgkgICAJaWRjLmZpcnN0KCk7CgkJaWRjLmluc2VydEFm
dGVyKCJjb25maWdfZmlsZV9saXN0IiwgZmlsZV9saXN0KTsKCX0KCWNhdGNoKEV4Y2VwdGlvbiBl
KQoJewoJCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUuZ2V0TWVzc2FnZSgpKTsKCX0KCgkv
LyBTZXR1cCBvdXRwdXQgbWVzc2FnZQoJaWRjLmZpcnN0KCk7CglpZGMuaW5zZXJ0QWZ0ZXIoInBr
Z19jb25maWciLGNvbmZpZ19kaXIpOwoKCWlkYy5kZXN0cm95KCk7</value>
</Values>
