<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get_file_name</value>
  <value name="encodeutf8">true</value>
  <value name="body">ICAgCUlEYXRhSGFzaEN1cnNvciBpZGMgPSBwaXBlbGluZS5nZXRIYXNoQ3Vyc29yKCk7CgoJLy8g
R2V0IGlucHV0IHZhbHVlcwogICAJaWRjLmZpcnN0KCAiZmlsZV9uYW1lIiApOwoJU3RyaW5nIGZp
bGVfbmFtZSA9IChTdHJpbmcpIGlkYy5nZXRWYWx1ZSgpOwoJaWRjLmZpcnN0KCAicGF0aCIgKTsK
CVN0cmluZyBwYXRoID0gKFN0cmluZykgaWRjLmdldFZhbHVlKCk7CgoJaWRjLmZpcnN0KCJ0eXBl
Iik7CglTdHJpbmcgdHlwZSA9IChTdHJpbmcpIGlkYy5nZXRWYWx1ZSgpOwoJaWYgKHR5cGUgPT0g
bnVsbCkKCQl0eXBlID0gIkxPQ0FMIjsgLy9EZWZhdWx0CgoJZmlsZV9uYW1lID0gZmlsZV9uYW1l
LnJlcGxhY2UoJyMnLCcwJyk7CglmaWxlX25hbWUgPSBmaWxlX25hbWUucmVwbGFjZSgnJicsJzAn
KTsKCVN0cmluZyBmdWxsX3BhdGggPSBwYXRoOwoJaWYgKHR5cGUuZXF1YWxzKCJGVFAiKSkKCQlm
dWxsX3BhdGggKz0gIi8iOwoJZWxzZQoJCWZ1bGxfcGF0aCArPSBGaWxlLnNlcGFyYXRvcjsKCWZ1
bGxfcGF0aCArPSBmaWxlX25hbWU7CgoJaWRjLmZpcnN0KCAiZmlsZSIgKTsKCWlkYy5pbnNlcnRB
ZnRlcigidmFsdWUiLGZ1bGxfcGF0aCk7CglpZGMuZGVzdHJveSgpOwo=</value>
</Values>
