<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">move</value>
  <value name="encodeutf8">true</value>
  <value name="body">ICAgCUlEYXRhSGFzaEN1cnNvciBpZGMgPSBwaXBlbGluZS5nZXRIYXNoQ3Vyc29yKCk7CgoJLy8g
R2V0IGlucHV0IHZhbHVlcwogICAJaWRjLmZpcnN0KCAic291cmNlIiApOwoJU3RyaW5nIHNvdXJj
ZSA9IChTdHJpbmcpIGlkYy5nZXRWYWx1ZSgpOwogICAJaWRjLmZpcnN0KCAidGFyZ2V0IiApOwoJ
U3RyaW5nIHRhcmdldCA9IChTdHJpbmcpIGlkYy5nZXRWYWx1ZSgpOwoJCgl0cnkKCXsKCQlGaWxl
IHNvdXJjZV9maWxlID0gbmV3IEZpbGUoc291cmNlKTsKCQlzb3VyY2VfZmlsZS5yZW5hbWVUbyhu
ZXcgRmlsZSh0YXJnZXQpKTsKCQlzb3VyY2VfZmlsZSA9IG51bGw7CgkKCSAgIAlpZGMuZmlyc3Qo
KTsKCQlpZGMuaW5zZXJ0QWZ0ZXIoInN0YXR1cyIsIlNVQ0NFU1MiKTsKCX0KCWNhdGNoKEV4Y2Vw
dGlvbiBlKQoJewoJICAgCWlkYy5maXJzdCgpOwoJCWlkYy5pbnNlcnRBZnRlcigic3RhdHVzIiwi
RVJST1IiKTsJCQoJCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUuZ2V0TWVzc2FnZSgpKTsK
CX0KCWlkYy5kZXN0cm95KCk7Cg==</value>
</Values>
